
server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql:///blog?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: postgres
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  
#邮箱配置（qq邮箱发送）
  mail:
    host: smtp.qq.com
    username: 943247920
    password: guznohdqqshwbdeh
  properties:
    mail:
      smtp:
         auth: true
         starttls:
           enable: true
           required: true
    
  thymeleaf:
    prefix: classpath:/templates/pages/
    cache: false
    suffix: .html
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sx.blog.common.pojo

  #